WebTravel/WebClient/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using WebClient.Areas.HelpPage.ModelDescriptions;

namespace WebClient.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

WebTravel/WebClient/Models/IdentityModels.cs
using System.Data.Entity;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace WebClient.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
        public string Hometown { get; set; }

        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DBTravelUser", throwIfV1Schema: false)
        {
        }

        public static ApplicationDbContext Create()
        {
            return new ApplicationDbContext();
        }
    }
}

WebTravel/WebClient/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using WebClient.Areas.HelpPage.ModelDescriptions;
using WebClient.Areas.HelpPage.Models;

namespace WebClient.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

WebTravel/WebClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace WebClient.Controllers
{
    
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Index1()
        {
            return View();
        }
    }
}

WebTravel/WebClient/Controllers/WebApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebClient.Controllers
{
    [RoutePrefix("Webapi")]
    public class WebApiController : Controller
    {
        // GET: WebApi
        
        [Route("~/")] // Domain
        [Route("")] // Domain/Controller
        [Route("Indes")] // Domain/Controller/Indes
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }

    }
}

WebTravel/WebClient/Views/Home/Index.cshtml
@section SPAViews {
    @Html.Partial("_Home")
}
@section Scripts{
    @*@Scripts.Render("~/bundles/knockout")
        @Scripts.Render("~/bundles/app")*@
    <script>
        $(document).ready(function () {
            var lista = $("#listPlaces");
            $.ajax({
                url: 'http://localhost:5390/api/Territories',
                type: 'GET',
                contentType: 'application/json',
                success: function (json) {
                    console.log("success");
                    lista.empty();
                    for (var k = 0; k < json.length; k++) {
                        lista.append("<li>" + json[k] + "</li>");
                    }
                },
                error: function (er) {
                    console.log("error");
                    lista.empty();
                    lista.append("<li>" + er.status + ': ' + er.statusText + "</li>");
                }
            });
        });
    </script>
}

WebTravel/WebClient/Views/Home/Index1.cshtml
@section SPAViews {
    @Html.Partial("_Home1")
}
@section Scripts{
<script src="~/Scripts/angular.js"></script>
    <script>
        var app = angular.module("myapp", [])
        .controller("myController", function ($scope, $http, $log) {

        var successCallBack = function (response) {
            $scope.success = response.data;
            $log.info(response);
        };
        var errorCallBack = function (response) {
            $scope.error = response.data;
            $log.info(response);
        };

        $http({
            method: "GET",
            url: "http://localhost:5390/api/Territories"
        }).then(successCallBack, errorCallBack);
    });
    </script>
}

WebTravel/WebClient/Views/Home/_Home.cshtml
<div class="jumbotron">
    <h1>Client Web Application</h1>
    <p class="lead">This Web is about Travel Recomendation</p>
    <abbr>I use ajax with Jquery</abbr>
</div>
<div class="row">
    <div class="col-xs-6">
        <h3>Top 10 Famous Places</h3>
        <ul id="listPlaces">            
        </ul>
    </div>
</div>

WebTravel/WebClient/Views/Home/_Home1.cshtml
<div ng-app="myapp">
    <div class="jumbotron">
        <h1>Client Web Application</h1>
        <p class="lead">This Web is about Travel Recomendation</p>
        <abbr>I use ajax with Angular</abbr>
    </div>
    <div class="row">
        <div class="col-xs-6">
            <div ng-controller="myController">
                <h3>Top 10 Famous Places</h3>
                <ul id="listPlaces">
                    <li ng-repeat="place in success">
                        {{place}}
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

WebTravel/WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Client Travel", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Home1", "Index1", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Private Info 'Salary'", "Index", "WebApi", new { area = "" }, null)</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @RenderSection("SPAViews", required: false)
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
</body>
</html>

WebTravel/WebClient/Views/WebApi/Index.cshtml
@{
    ViewBag.Title = "Cash Flow";
}

<h1>All Salary...</h1>

<h2 id="h2"></h2>
<a href="">State</a>
<input type="button" id="logOut" value="Log Out" />
<ul id="list"> </ul>


<script src="Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        
        $("#h2").text("Hello " + localStorage.getItem('userName'));

        $("#logOut").click(function () {
            sessionStorage.removeItem('accessToken');
            window.location.href = "Login.html";
        });

        $.ajax({
            method: 'GET',
            url: 'http://localhost:5390/api/Territories/Unit',
            headers: {
                Authorization: "bearer " + sessionStorage.getItem('accessToken')
            },
            success: function (response) {
                console.log("Success");
                for (var i = 0; i < response.length; i++) {
                    $("#list").append("<li> First Name: " + response[i].FirstName + " Last Name: " + response[i].LastName + " Unit Price: " + response[i].UnitPrice + "</li><br>");
                }
            },
            error: function (e) {
                console.log("Error");
                if (e.status == "401") {
                    window.location.href = "@Url.Action("Login")";
                }
            }
        })
    });
</script>

WebTravel/WebClient/Views/WebApi/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
<div class="col-md-11 col-md-offset-1">
    <div class="well">
        <!--This table contains the fields that we want to capture to register a new user-->
        <table class="table table-bordered">
            <thead>
                <tr class="success">
                    <th colspan="2">
                        User Login
                        <a class="btn btn-success pull-right" href="@Url.Action("Register")">Register</a>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Username</td>
                    <td><input type="text" id="txtUsername" placeholder="Username" /> </td>
                </tr>
                <tr>
                    <td>Password</td>
                    <td>
                        <input type="password" id="txtPassword"
                               placeholder="Password" />
                    </td>
                </tr>
                <tr class="success">
                    <td colspan="2">
                        <input id="btnLogin" class="btn btn-success"
                               type="button" value="Login" />
                    </td>
                </tr>
            </tbody>
        </table>
        <table class="table table-bordered">
            <thead>
                <tr class="success">
                    <th>Social Login</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <input type="button" id="btnLoginGoogle" class="btn btn-success" value="Login with Google" />
                    </td>
                </tr>
            </tbody>
        </table>
        <!--Bootstrap alert to display any validation errors-->
        <div id="divError" class="alert alert-danger collapse">
            <a id="linkClose" href="#" class="close">&times;</a>
            <div id="divErrorText"></div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script>
    $(document).ready(function () {
        $("#btnLogin").click(function () {
            $.ajax({
                url: "http://localhost:5390/token",
                method: 'POST',
                contentType: "application/json",
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded'
                },
                data: {
                    username: $("#txtUsername").val(),
                    password: $("#txtPassword").val(),
                    grant_type: 'password'
                },
                success: function (responde) {
                    console.log("Success");
                    sessionStorage.setItem('userName', responde.userName);
                    sessionStorage.setItem('accessToken', responde.access_token);

                    //Test response
                    //$("#diverror").text(JSON.stringify(response));
                    window.location.href = "@Url.Action("Index")";
                },
                error: function (jqXHR) {
                    console.log("Error");
                    $('#divErrorText').text(jqXHR.responseText);
                    $('#divError').show('fade');

                }
            });
        });
    });
</script>

WebTravel/WebClient/Views/WebApi/Register.cshtml
@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>
<div class="col-md-11 col-md-offset-1">
    <div class="well">
        <!--This table contains the fields that we want to capture to register a new user-->
        <table class="table table-bordered">
            <thead>
                <tr class="success">
                    <th colspan="2">
                        New User Registration
                        <a class="btn btn-success pull-right" href="@Url.Action("Login")">Login</a>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Email</td>
                    <td><input type="text" id="txtEmail" placeholder="Email" /> </td>
                </tr>
                <tr>
                    <td>Password</td>
                    <td>
                        <input type="password" id="txtPassword"
                               placeholder="Password" />
                    </td>
                </tr>
                <tr>
                    <td>Confirm Password</td>
                    <td>
                        <input type="password" id="txtConfirmPassword"
                               placeholder="Confirm Password" />
                    </td>
                </tr>
                <tr class="success">
                    <td colspan="2">
                        <input id="btnRegister" class="btn btn-success"
                               type="button" value="Register" />
                    </td>
                </tr>
            </tbody>
        </table>
        <!--Bootstrap modal dialog that shows up when regsitration is successful-->
        <div class="modal fade" tabindex="-1" id="successModal"
             data-keyboard="false" data-backdrop="static">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            &times;
                        </button>
                        <h4 class="modal-title">Success</h4>
                    </div>
                    <div class="modal-body">
                        <form>
                            <h2 class="modal-title">Registration Successful!</h2>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success"
                                data-dismiss="modal">
                            Close
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <!--Bootstrap alert to display any validation errors-->
        <div id="divError" class="alert alert-danger collapse">
            <a id="linkClose" href="#" class="close">&times;</a>
            <div id="divErrorText"></div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {

        //Close the bootstrap alert
        $('#linkClose').click(function () {
            $('#divError').hide('fade');
        });

        // Save the new user details
        $('#btnRegister').click(function () {
            $.ajax({
                url: 'http://localhost:5390/api/account/register',
                method: 'POST',
                data: {
                    email: $('#txtEmail').val(),
                    password: $('#txtPassword').val(),
                    confirmPassword: $('#txtConfirmPassword').val()
                },
                success: function () {
                    console.log('Success');
                    $('#successModal').modal('show');
                },
                error: function (jqXHR) {
                    console.log('Error');
                    $('#divErrorText').text(jqXHR.responseText);
                    $('#divError').show('fade');
                }
            });
        });
    });
</script>